# Generated by Django 4.1.7 on 2023-04-30 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("grade", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.ManyToManyField(
                through="myapp.StudentUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(null=True)),
                ("add_score", models.IntegerField(default=0, null=True)),
                ("date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField(auto_now_add=True)),
                ("checkin_text", models.CharField(max_length=200)),
                (
                    "checkin_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="checkin_images"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
            ],
        ),
    ]
