# Generated by Django 4.1.7 on 2023-04-30 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_remove_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.ManyToManyField(
                null=True, through="myapp.StudentUser", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
