# Generated by Django 3.2.18 on 2023-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
