# Generated by Django 3.2.18 on 2023-05-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230501_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
