# Generated by Django 3.2.18 on 2023-05-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_checkin_checkin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='Classes',
        ),
    ]
