# Generated by Django 3.2.18 on 2023-05-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230511_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Classes',
        ),
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(default='NewDream', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.classes'),
            preserve_default=False,
        ),
    ]
