# Generated by Django 3.2.18 on 2023-05-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230511_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classes',
            new_name='Classes',
        ),
    ]
