# Generated by Django 4.2.1 on 2023-05-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_student_consecutive"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("message", models.TextField()),
            ],
        ),
    ]
